# Use the official Node.js image with LTS version as a base image
FROM node:20 as build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Angular application
RUN npm run build --prod

# Use a lightweight Nginx image to serve the Angular app
FROM nginx:alpine

# Copy the built Angular app from the previous stage to the Nginx web root
COPY --from=build /app/dist/* /usr/share/nginx/html/

# Expose the port used by Nginx (usually 80 by default)
EXPOSE 80

# Nginx runs in the foreground when started
CMD ["nginx", "-g", "daemon off;"]

# FROM node:20.8.1
# RUN mkdir -p /usr/src/app
# WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm install
# RUN npm install -g @angular/cli@17
# COPY . .
# RUN npm run build

# CMD ["npm", "start"]